#builders:
#  autoRouteGenerator:
#    import: "package:auto_route_generator/builder.dart"
#    builder_factories: ["autoRouteGenerator"]
#    build_extensions: {'.dart': ['.gr.dart']}
#    required_inputs: ['.g.dart']
#    auto_apply: dependents
#    build_to: source
builders:
  autoRouterBuilder:
    import: "package:auto_route_generator/builder.dart"
    builder_factories: [ "autoRouterBuilder" ]
    build_extensions: { '.dart': [ '.gr.json' ] }
    runs_before: [ 'auto_route_generator:autoRouteBuilder' ]
    auto_apply: dependents
    build_to: cache
  autoRouteBuilder:
    import: "package:auto_route_generator/builder.dart"
    builder_factories: [ "autoRouteBuilder" ]
    required_inputs: [ '.g.dart' ]
    build_extensions: { "lib/$lib$": [ "lib/router.dart" ] }
    auto_apply: root_package
    build_to: source